require 'mandao/version'
require 'mandao/xml_format'
require 'mandao/resources/base'
require 'mandao/resources/address'
require 'mandao/resources/address_list'
require 'mandao/resources/document'
require 'mandao/configuration'